### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by short-dsb** [remarkjs/remark-gemoji#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.0.0

### Link to runnable example

Node 20, npm 10

### Steps to reproduce

1. Build or run project

### Expected behavior

No console warnings.

### Actual behavior

Console warning for missing source map:

```bash
WARNING in ./node_modules/remark-emoji/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/remark-emoji/index.js.map' file: Error: ENOENT: no such file or directory, open './node_modules/remark-emoji/index.js.map'
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8, Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
Welcome @short-dsb! 👋 
There is no source map, because there is nothing to map in the first place.
It is JavaScript already and the source delivered without modification to NPM.

**Comment by wooorm** [comment]
`remark-emoji` is also not `remark-gemoji` ;)

**Comment by short-dsb** [comment]
Got it. 🙂 In case anyone else comes across this, I added `/remark-emoji/` to the `excludes` for Webpack’s `source-map-loader` to suppress the warnings.

**Comment by ChristianMurphy** [comment]
@short-dsb depending on what you mean.
There should be no error for `remark-gemoji`, as there is no mapping.
The error is correct if you mean `remark-emoji` that is TypeScript based and does not provide a map file. That can be raised with the maintainers at https://github.com/rhysd/remark-emoji/issues

**Comment by short-dsb** [comment]
Ah… my apologies. Google led me astray. 😞 Thank for your patience!
